version: 2.1

orbs:
  codacy: codacy/base@1.0.0

jobs:
  build_docker_image:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: |
            docker build -t $CIRCLE_PROJECT_REPONAME:latest .
            docker run $CIRCLE_PROJECT_REPONAME:latest codacy_prospector_test.py
            docker save --output ~/workdir/docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
      - persist_to_workspace:
          paths:
            - workdir/*
          root: ~/
workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version
      - build_docker_image:
          requires:
            - codacy/checkout_and_version
      - codacy/shell:
          name: publish_dockerhub
          context: CodacyDocker
          cmd: |
            docker load --input ~/workdir/docker-image.tar
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:latest
            docker push codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker push codacy/$CIRCLE_PROJECT_REPONAME:latest
          requires:
            - build_docker_image
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - publish_dockerhub
