version: 2.1

orbs:
  codacy: codacy/base@10.8.0
  codacy_plugins_test: codacy/plugins-test@1.1.1

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version
      - codacy/shell:
          name: publish_docker_local
          cmd: |
            docker build -t $CIRCLE_PROJECT_REPONAME:latest .
            docker run $CIRCLE_PROJECT_REPONAME:latest codacy_prospector_test.py
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          run_json_tests: false
          run_pattern_tests: false
          requires:
            - publish_docker_local
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - publish_docker_local
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - codacy/publish_docker
