output-format: grouped

strictness: veryhigh
doc-warnings: true
test-warnings: false
max-line-length: 120
autodetect: false

ignore-paths:
  - docs/

frosted:
  run: false

pyroma:
  run: true

pylint:
  disable:
    - bad-builtin
    - too-few-public-methods
    - missing-docstring
    - star-args
    - use-symbolic-message-instead

pep8:
  full: true
  disable:
    - E126

pep257:
  disable:
    - D100
    - D101
    - D102
    - D103
    - D205
    - D400
    - D401
    - D415

vulture:
  disable:
    - unused-variable
    - unused-function